.mode columns
.headers ON
PRAGMA foreign_keys=ON;

DROP TABLE IF EXISTS JOGO;
DROP TABLE IF EXISTS ESTATISTICASJOGADOR;
DROP TABLE IF EXISTS ESTATISTICASEQUIPA;
DROP TABLE IF EXISTS ESTATISTICASJOGO;
DROP TABLE IF EXISTS ESTADO;
DROP TABLE IF EXISTS GRUPO;
DROP TABLE IF EXISTS EQUIPA;
DROP TABLE IF EXISTS JOGADOR;

CREATE TABLE JOGADOR(
    nomeJogador VARCHAR(255) NOT NULL PRIMARY KEY,
    nGolos TINYINT NOT NULL,
    nacionalidade VARCHAR(255) NOT NULL,
    numero TINYINT NOT NULL,
    jogosJogados TINYINT NOT NULL,
    tempoJogado TINYINT NOT NULL
);


CREATE TABLE EQUIPA(
    nomeEquipa VARCHAR(255)  NOT NULL PRIMARY KEY,
    jogosJogados TINYINT NOT NULL,
    golosTotais TINYINT NOT NULL,
);

CREATE TABLE GRUPO(
    idGrupo TINYINT NOT NULL PRIMARY KEY
);

CREATE TABLE ESTADO(
    tipoEstado VARCHAR(255) NOT NULL PRIMARY KEY,
    CONSTRAINT check_tipoEstado CHECK (tipoEstado == 'grupos' OR tipoEstado == 'oitavos' OR tipoEstado == 'quartos' OR tipoEstado == 'semis' OR tipoEstado == 'final')
);

CREATE TABLE ESTATISTICASDEJOGO(
    tipoJogo VARCHAR(255) NOT NULL,
    resultado VARCHAR(255) NOT NULL,
    nFaltas VARCHAR(255) NOT NULL,
    posseDeBola VARCHAR(255) NOT NULL,
    cantos VARCHAR(255) NOT NULL,
    remates VARCHAR(255) NOT NULL,
    passesCompletos VARCHAR(255) NOT NULL,
    rematesABaliza VARCHAR(255) NOT NULL
);

CREATE TABLE ESTATISTICASEQUIPA(
    nPontos TINYINT NOT NULL,
    classificacao TINYINT NOT NULL,
    golosMarcados TINYINT NOT NULL,
    golosSofridos TINYINT NOT NULL,
    vitorias TINYINT NOT NULL,
    derrotas TINYINT NOT NULL,
    empates TINYINT NOT NULL
);

CREATE TABLE ESTATISTICASJOGADOR(
    golosMarcados TINYINT NOT NULL,
    assistencias TINYINT NOT NULL,
    passesRealizados INT NOT NULL
    cortesRealizados INT NOT NULL,
    cartoesAmarelos TINYINT NOT NULL,
    cartoesVermelhos TINYINT NOT NULL,
    faltasCometidas TINYINT NOT NULL,
    golosDefendidos INT NOT NULL,
);

CREATE TABLE JOGO(
    idJogo VARCHAR(255) NOT NULL PRIMARY KEY,
    eliminatoria VARCHAR(255) NOT NULL REFERENCES ESTADO(tipoEstado),
    nGolosVisitante TINYINT NOT NULL,
    nGolosVisitada TINYINT NOT NULL,
    Data VARCHAR(255) NOT NULL
);


SELECT * FROM JOGADOR;
SELECT * FROM EQUIPA;
SELECT * FROM GRUPO;
SELECT * FROM ESTADO;
SELECT * FROM ESTATISTICASJOGO;
SELECT * FROM ESTATISTICASEQUIPA;
SELECT * FROM ESTATISTICASJOGADOR;
SELECT * FROM JOGO;

-.read povoar.sql